Admin/Administrator/Controllers/GrupoUsuariosController.cs
using Administrator.Util;
using Api.Enums;
using Api.Models;
using Api.Models.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Administrator.Controllers
{
    public class GrupoUsuariosController : AuthController
    {
        [Permissao(PermissionamentoController.GrupoUsuarios, TipoPermissionamento.Listar)]
        public ActionResult Index()
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            List<GrupoUsuariosModel> grupos = api.Get<List<GrupoUsuariosModel>>("api/GrupoUsuarios/ListarGrupos");
            if (grupos == null)
                grupos = new List<GrupoUsuariosModel>();

            return View(grupos);
        }

        [Permissao(PermissionamentoController.GrupoUsuarios, TipoPermissionamento.Criar)]
        public ActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [Permissao(PermissionamentoController.GrupoUsuarios, TipoPermissionamento.Criar)]
        public ActionResult Criar(GrupoUsuariosModel model)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            RetornoRequest retorno = api.Post<RetornoRequest>("api/GrupoUsuarios/Incluir", model);
            return Json(new { Status = retorno.Retorno, Mensagem = retorno.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Permissao(PermissionamentoController.GrupoUsuarios, TipoPermissionamento.Editar)]
        public ActionResult Editar(int codigo)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            GrupoUsuariosModel model = api.Get<GrupoUsuariosModel>($"api/GrupoUsuarios/ObterGrupo?codigo={codigo}");
            if (model == null)
            {
                TempData["Mensagem"] = "Não foi encontrado o Grupo de Usuários selecionado.";
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        [Permissao(PermissionamentoController.GrupoUsuarios, TipoPermissionamento.Editar)]
        public ActionResult Editar(GrupoUsuariosModel model)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            RetornoRequest retorno = api.Post<RetornoRequest>("api/GrupoUsuarios/editar", model);
            TempData["Mensagem"] = retorno.Mensagem;
            return Json(new { Status = retorno.Retorno, Mensagem = retorno.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Permissao(PermissionamentoController.GrupoUsuarios, TipoPermissionamento.Excluir)]
        public JsonResult Excluir(int codigo)
        {
            string Mensagem = string.Empty;
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            Boolean retorno = (Boolean)api.Get<Object>($"api/GrupoUsuarios/Excluir?codigo={codigo}");

            if (!retorno)
                Mensagem = "Não foi possível remover o cadastro financeiro";
            else
                Mensagem = "Cadastro financeiro removido com sucesso.";

            return Json(new { Status = retorno, Mensagem = Mensagem }, JsonRequestBehavior.AllowGet);
        }
    }
}

Admin/Administrator/Views/GrupoUsuarios/Criar.cshtml
<script src="~/Scripts/GrupoUsuarios/Permissionamento.js"></script>
<script src="~/Scripts/GrupoUsuarios/GrupoUsuarios.js"></script>
<script src="~/Scripts/GrupoUsuarios/Criar.js"></script>
<script src="~/Scripts/GrupoUsuarios/FuncoesGrupoUsuarios.js"></script>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card material-table">
                <div class="card-content">
                    <div class="row titulo">
                        <div class="col s12">
                            <h4>Criar Grupo de Usuário</h4>
                        </div>
                    </div>  
                    <form id="formGrupo">
                        <div class="row">
                            <div class="input-field col s6">
                                <label for="NomeGrupo">Nome do Grupo <span class="obrigatorio">*</span></label>
                                @Html.TextBox("NomeGrupo", string.Empty, new { @required = "required" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="table-header">
                                <span class="table-title">Permissões</span>
                            </div>
                            <div class="row">
                                <table class="highlight responsive-table" id="tabelaGrupo">
                                    <thead>
                                        <tr>
                                            <th width="15%">Módulo</th>
                                            <th class="center desabilita-ordenacao"></th>
                                            <th width="18%" class="center desabilita-ordenacao">Listar </th>
                                            <th width="18%" class="center desabilita-ordenacao">Incluir</th>
                                            <th width="18%" class="center desabilita-ordenacao">Editar</th>
                                            <th width="18%" class="center desabilita-ordenacao">Excluir</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td></td>
                                            <td><p class="left"><input type="checkbox" id="0_0" /><label for="0_0"></label></p></td>
                                            <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="0_4" /><label for="0_4"></label></p></td>
                                            <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="0_1" /><label for="0_1"></label></p></td>
                                            <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="0_2" /><label for="0_2"></label></p></td>
                                            <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="0_3" /><label for="0_3"></label></p></td>
                                        </tr>
                                        @foreach (Api.Enums.PermissionamentoController item in Enum.GetValues(typeof(Api.Enums.PermissionamentoController)))
                                        {
                                            if (item == Api.Enums.PermissionamentoController.Nulo)
                                            {
                                                continue;
                                            }

                                            <tr>
                                                <td>@item</td>
                                                <td><p class="left"><input type="checkbox" id="@((int)item)_0" /><label for="@((int)item)_0"></label></p></td>
                                                <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="@((int)item)_4" /><label for="@((int)item)_4"></label></p></td>
                                                <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="@((int)item)_1" /><label for="@((int)item)_1"></label></p></td>
                                                <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="@((int)item)_2" /><label for="@((int)item)_2"></label></p></td>
                                                <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="@((int)item)_3" /><label for="@((int)item)_3"></label></p></td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("~/Views/Shared/Partial/SalvarBotoesPartial.cshtml")
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Admin/Administrator/Views/GrupoUsuarios/Editar.cshtml
@model Api.Models.Model.GrupoUsuariosModel

<script src="~/Scripts/GrupoUsuarios/Permissionamento.js"></script>
<script src="~/Scripts/GrupoUsuarios/GrupoUsuarios.js"></script>
<script src="~/Scripts/GrupoUsuarios/Editar.js"></script>
<script src="~/Scripts/GrupoUsuarios/FuncoesGrupoUsuarios.js"></script>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card material-table">
                <div class="card-content">
                    <div class="row titulo">
                        <div class="col s12">
                            <h4>Editar Grupo de Usuário</h4>
                        </div>
                    </div>
                    @Html.Hidden("Model", Json.Encode(Model))
                    <form id="formGrupo">
                        <div class="row">
                            <div class="input-field col s6">
                                <label for="NomeGrupo">Nome do Grupo <span class="obrigatorio">*</span></label>
                                @Html.TextBoxFor(model => model.Nome, string.Empty, new { @required = "required" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="table-header">
                                <span class="table-title">Permissões</span>
                            </div>
                            <div class="row">
                                <table class="highlight responsive-table" id="tabelaGrupo">
                                    <thead>
                                        <tr>
                                            <th width="15%">Módulo</th>
                                            <th class="center desabilita-ordenacao"></th>
                                            <th width="18%" class="center desabilita-ordenacao">Listar </th>
                                            <th width="18%" class="center desabilita-ordenacao">Incluir</th>
                                            <th width="18%" class="center desabilita-ordenacao">Editar</th>
                                            <th width="18%" class="center desabilita-ordenacao">Excluir</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td></td>
                                            <td><p class="left"><input type="checkbox" id="0_0" /><label for="0_0"></label></p></td>
                                            <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="0_4" /><label for="0_4"></label></p></td>
                                            <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="0_1" /><label for="0_1"></label></p></td>
                                            <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="0_2" /><label for="0_2"></label></p></td>
                                            <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="0_3" /><label for="0_3"></label></p></td>
                                        </tr>
                                        @foreach (Api.Enums.PermissionamentoController item in Enum.GetValues(typeof(Api.Enums.PermissionamentoController)))
                                        {
                                            if (item == Api.Enums.PermissionamentoController.Nulo)
                                            {
                                                continue;
                                            }

                                            <tr>
                                                <td>@item</td>
                                                <td><p class="left"><input type="checkbox" id="@((int)item)_0" /><label for="@((int)item)_0"></label></p></td>
                                                <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="@((int)item)_4" /><label for="@((int)item)_4"></label></p></td>
                                                <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="@((int)item)_1" /><label for="@((int)item)_1"></label></p></td>
                                                <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="@((int)item)_2" /><label for="@((int)item)_2"></label></p></td>
                                                <td><p class="center" style="margin-left: 18px;"><input type="checkbox" id="@((int)item)_3" /><label for="@((int)item)_3"></label></p></td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("~/Views/Shared/Partial/SalvarBotoesPartial.cshtml")
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Admin/Administrator/Views/GrupoUsuarios/Index.cshtml
@model List<Api.Models.Model.GrupoUsuariosModel>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card material-table">
                <div class="card-content">
                    <div class="table-header">
                        <span class="table-title">Listagem de Grupo de Usuários</span>
                        <div class="actions">
                            <a href="@Url.Action("Criar")" class="waves-effect btn-flat nopadding"><i class="material-icons">add_circle</i></a>
                            <a href="#" class="search-toggle waves-effect btn-flat nopadding"><i class="material-icons">search</i></a>
                        </div>
                    </div>
                    <div class="row">
                        <table class="highlight dataTable responsive-table" id="tabelaFinanceiro">
                            <thead>
                                <tr>
                                    <th>Nome do Grupo</th>
                                    <th class="desabilita-ordenacao"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Nome</td>
                                        <td>
                                            <a class="icone-clicavel" onclick="ExcluirGrupo('@item.Codigo')"><i class="material-icons">&#xE872;</i></a>
                                            <a class="icone-clicavel" href="@Url.Action("Editar", "GrupoUsuarios", new { codigo = item.Codigo })"><i class="material-icons">&#xE254;</i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {

    <script>
        var ExcluirGrupo = function (codigo) {
            //var msg = 'Removendo registro...aguarde!';
            $.blockUI({ message: 'Removendo registro...aguarde!' });

            $.ajax({
                type: "POST",
                url: "@Url.Action("Excluir", "GrupoUsuarios")",
                data: { codigo: codigo },
                success: function (data) {
                    if (data.Status)
                    {
                        Materialize.toast(data.Mensagem, 2000);
                        setTimeout(function () {
                            window.location.reload();
                        }, 2000);
                    }
                },
                dataType: "json"
            });
        }
    </script>
}