Admin/Administrator/Controllers/FinanceiroController.cs
using Administrator.Util;
using Api.Enums;
using Api.Models;
using Api.Models.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Administrator.Controllers
{
    public class FinanceiroController : AuthController
    {
        // GET: Financeiro
        [Permissao(PermissionamentoController.Financeiro, TipoPermissionamento.Listar)]
        public ActionResult Index()
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            List<FinanceiroModel> financeiro = api.Get<List<FinanceiroModel>>("api/financeiro/ListarCadastrosFinanceiros");
            if (financeiro == null)
                financeiro = new List<FinanceiroModel>();

            return View(financeiro);
        }

        [Permissao(PermissionamentoController.Financeiro, TipoPermissionamento.Criar)]
        public ActionResult Criar()
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            List<ClienteModel> clientes = api.Get<List<ClienteModel>>("api/Clientes/ObterLista");
            if(clientes.Count == 0)
            {
                //Emitir Mensagem
                return RedirectToAction("Index");
            }

            ParametrosModel parametro = api.Get<ParametrosModel>("api/Parametros/ObterParametros");
            if (parametro != null)
            {
                clientes = clientes.Where(x => x.Codigo != parametro.ClienteDefault).ToList();
            }

            TempData["Clientes"] = clientes.Where(x => x.StatusCliente == Situacao.ATIVO).Select(cli => new SelectListItem {
                Value = cli.Codigo.ToString(),
                Text = cli.Nome
            });

            return View();
        }

        [HttpPost]
        [Permissao(PermissionamentoController.Financeiro, TipoPermissionamento.Criar)]
        public ActionResult Criar(FinanceiroModel model)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            RetornoRequest retorno = api.Post<RetornoRequest>("api/Financeiro/Incluir", model);
            return Json(new { Status = retorno.Retorno, Mensagem = retorno.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Permissao(PermissionamentoController.Financeiro, TipoPermissionamento.Editar)]
        public ActionResult Editar(int clienteCodigo, string documento)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            FinanceiroModel model = api.Get<FinanceiroModel>($"api/financeiro/obtercadastrofinanceiro?clienteCodigo={clienteCodigo}&documento={documento}");
            List<ClienteModel> clientes = api.Get<List<ClienteModel>>("api/Clientes/ObterLista");
            TempData["Clientes"] = clientes.Select(cli => new SelectListItem
            {
                Value = cli.Codigo.ToString(),
                Text = cli.Nome
            });

            if (model == null)
            {
                TempData["Mensagem"] = "Não foi encontrado o cadastro financeiro selecionado.";
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        [Permissao(PermissionamentoController.Financeiro, TipoPermissionamento.Editar)]
        public ActionResult Editar(FinanceiroModel model)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            RetornoRequest retorno = api.Post<RetornoRequest>("api/financeiro/editar", model);
            TempData["Mensagem"] = retorno.Mensagem;
            return Json(new { Status = retorno.Retorno, Mensagem = retorno.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Permissao(PermissionamentoController.Financeiro, TipoPermissionamento.Excluir)]
        public JsonResult Excluir(int clienteCodigo, string documento)
        {
            string Mensagem = string.Empty;
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            Boolean retorno = (Boolean)api.Get<Object>($"api/financeiro/Excluir?clienteCodigo={clienteCodigo}&documento={documento}");

            if (!retorno)
                Mensagem = "Não foi possível remover o cadastro financeiro";
            else
                Mensagem = "Cadastro financeiro removido com sucesso.";

            return Json(new { Status = retorno, Mensagem = Mensagem }, JsonRequestBehavior.AllowGet);
        }
    }
}

Admin/Administrator/Views/Financeiro/Criar.cshtml
@model Api.Models.Model.FinanceiroModel

<script src="~/Scripts/Financeiro/Financeiro.js"></script>
<script src="~/Scripts/Financeiro/Criar.js"></script>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <div class="row titulo">
                        <div class="col s12">
                            <h4>Criar Cadastro Financeiro</h4>
                        </div>
                    </div>
                    <h5 class="classe-subtitulo">Informações Gerais</h5>
                    <div class="row">
                        <form action="@Url.Action("Criar")" id="EnviarFinanceiro" method="post" enctype="application/x-www-form-urlencoded">
                            <div class="row">
                                <div class="input-field col s6">
                                    @Html.DropDownListFor(model => model.ClienteCodigo, TempData["Clientes"] as IEnumerable<SelectListItem>, new { @class = "validate", @required = "required" })
                                    <label for="ClienteCodigo">Cliente <span class="obrigatorio">*</span></label>
                                </div>
                                <div class="col s2">
                                    <label for="Emissao">Data de Emissão <span class="obrigatorio">*</span></label>
                                    <input type="date" id="Emissao" nome="Emissao" class="datepicker" required maxlength="10" />
                                </div>
                                <div class="col s2">
                                    <label for="Vencimento">Data de Vencimento <span class="obrigatorio">*</span></label>
                                    <input type="date" id="Vencimento" nome="Vencimento" class="datepicker" required maxlength="10" />
                                </div>
                                <div class="col s2">
                                    <label for="Pagamento">Data de Pagamento</label>
                                    <input type="date" id="Pagamento" nome="Pagamento" class="datepicker" maxlength="10" />
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                    <label for="Documento">Nº Documento <span class="obrigatorio">*</span></label>
                                    @Html.TextBoxFor(model => model.Documento, new { @class = "validate", @required = "required" })
                                </div>
                                <div class="input-field col s3">
                                    <label for="Valor">Valor <span class="obrigatorio">*</span></label>
                                    <input type="text" id="Valor" name="Valor" class="formata-currency validate" required maxlength="17" />
                                </div>
                            </div>
                            @Html.Partial("~/Views/Shared/Partial/SalvarBotoesPartial.cshtml")
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Admin/Administrator/Views/Financeiro/Editar.cshtml
@model Api.Models.Model.FinanceiroModel

<script src="~/Scripts/Financeiro/Financeiro.js"></script>
<script src="~/Scripts/Financeiro/Editar.js"></script>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <div class="row titulo">
                        <div class="col s12">
                            <h4>Editar Cadastro Financeiro</h4>
                        </div>
                    </div>
                    <h5 class="classe-subtitulo">Informações Gerais</h5>
                    <div class="row">
                        <form action="@Url.Action("Editar")" id="EnviarFinanceiro" method="post" enctype="application/x-www-form-urlencoded">
                            <div class="row">
                                <div class="input-field col s6">
                                    @Html.DropDownListFor(model => model.ClienteCodigo, TempData["Clientes"] as IEnumerable<SelectListItem>, new { @class = "validate", @required = "required", @disabled = true })
                                    <label for="ClienteCodigo">Cliente <span class="obrigatorio">*</span></label>
                                </div>
                                <div class="col s2">
                                    <label for="Emissao">Data de Emissão <span class="obrigatorio">*</span></label>
                                    <input type="text" id="Emissao" nome="Emissao" class="datepicker" required maxlength="10" />
                                </div>
                                <div class="col s2">
                                    <label for="Vencimento">Data de Vencimento <span class="obrigatorio">*</span></label>
                                    <input type="text" id="Vencimento" nome="Vencimento" class="datepicker" required maxlength="10" />
                                </div>
                                <div class="col s2">
                                    <label for="Pagamento">Data de Pagamento <span class="obrigatorio">*</span></label>
                                    <input type="date" id="Pagamento" nome="Pagamento" class="datepicker" maxlength="10" />
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                    <label for="Documento">Nº Documento <span class="obrigatorio">*</span></label>
                                    @Html.TextBoxFor(model => model.Documento, new { @class = "validate", @required = "required", @readonly = "readonly" })
                                </div>
                                <div class="input-field col s3">
                                    <label for="Valor">Valor <span class="obrigatorio">*</span></label>
                                    <input type="text" id="Valor" name="Valor" class="formata-currency validate" value="@Model.Valor" required maxlength="17" />
                                </div>
                            </div>
                            @Html.Partial("~/Views/Shared/Partial/SalvarBotoesPartial.cshtml")
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    @if (Model.Pagamento.HasValue)
    {
        <script>
            //Inicializa valores do picker
            $("#Pagamento").pickadate().pickadate('picker').set('select', '@Model.Pagamento.Value.ToShortDateString()');
        </script>
    }
    <script>
    $(document).ready(function () {
        $('#ClienteCodigo').material_select();

        //inicializa o picker
        $("#Emissao").click(function (event) {
            event.stopPropagation();
            $("#Emissao").pickadate("picker").open();
        });
        $("#Emissao").pickadate().pickadate('picker').set('select', '@Model.Emissao.ToShortDateString()');

        $("#Vencimento").click(function (event) {
            event.stopPropagation();
            $("#Vencimento").pickadate("picker").open();
        });
        $("#Vencimento").pickadate().pickadate('picker').set('select', '@Model.Vencimento.ToShortDateString()');

        $("#Pagamento").click(function (event) {
            event.stopPropagation();
            $("#Pagamento").pickadate("picker").open();
        });
    });
    </script>
}

Admin/Administrator/Views/Financeiro/Index.cshtml
@model List<Api.Models.Model.FinanceiroModel>

<script src="~/Scripts/Financeiro/Index.js"></script>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card material-table">
                <div class="card-content">
                    <div class="table-header">
                        <span class="table-title">Listagem de Cadastro Financeiro</span>
                        <div class="actions">
                            <a href="@Url.Action("Criar")" class="waves-effect btn-flat nopadding"><i class="material-icons">add_circle</i></a>
                            <a href="#" class="search-toggle waves-effect btn-flat nopadding"><i class="material-icons">search</i></a>
                        </div>
                    </div>
                    <div class="row">
                        <table class="highlight dataTable responsive-table" id="tabelaFinanceiro">
                            <thead>
                                <tr>
                                    <th>Nome do Cliente</th>
                                    <th>Nº Documento</th>
                                    <th>Data de Emissão</th>
                                    <th>Data de Vencimento</th>
                                    <th>Data de Pagamento</th>
                                    <th>Valor</th>
                                    <th class="desabilita-ordenacao"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Cliente.Nome</td>
                                        <td>@item.Documento</td>
                                        <td>@item.Emissao.ToShortDateString()</td>
                                        <td>@item.Vencimento.ToShortDateString()</td>
                                        <td>@if (item.Pagamento.HasValue) { @item.Pagamento.Value.ToShortDateString() }</td>
                                        <td>@item.Valor</td>
                                        <td>
                                            <a class="icone-clicavel" onclick="ExcluirFinanceiro('@item.ClienteCodigo','@item.Documento')"><i class="material-icons">&#xE872;</i></a>
                                            <a class="icone-clicavel" href="@Url.Action("Editar", "Financeiro", new { clienteCodigo = item.ClienteCodigo, documento = item.Documento })"><i class="material-icons">&#xE254;</i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>