Admin/Administrator/Controllers/PlanoPagamentoController.cs

using Administrator.Util;
using Api.Enums;
using Api.Models;
using Api.Models.Model;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Administrator.Controllers
{
    public class PlanoPagamentoController : AuthController
    {
        // GET: Vendedor
        [Permissao(PermissionamentoController.PlanoPagamento, TipoPermissionamento.Listar)]
        public ActionResult Index()
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);

            List<PlanoPagamentoModel> planoPagamento = api.Get<List<PlanoPagamentoModel>>("api/PlanoPagamento/obterlista");
            if (planoPagamento == null)
                planoPagamento = new List<PlanoPagamentoModel>();

            return View(planoPagamento);
        }

        [Permissao(PermissionamentoController.PlanoPagamento, TipoPermissionamento.Criar)]
        public ActionResult Criar()
        {
            return View(new PlanoPagamentoModel());
        }

        [HttpPost]
        [Permissao(PermissionamentoController.PlanoPagamento, TipoPermissionamento.Criar)]
        public ActionResult Criar(PlanoPagamentoModel novoPlanoPagamento)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            RetornoRequest retorno = api.Post<RetornoRequest>("api/PlanoPagamento/Incluir", novoPlanoPagamento);
            return Json(new { Status = retorno.Retorno, Mensagem = retorno.Mensagem }, JsonRequestBehavior.AllowGet);
        }

        [Permissao(PermissionamentoController.PlanoPagamento, TipoPermissionamento.Editar)]
        public ActionResult Editar(int id)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);

            PlanoPagamentoModel planoPagamento = api.Get<PlanoPagamentoModel>($"api/PlanoPagamento/ObterPlano?codigo={id}");
            if (planoPagamento == null)
            {
                TempData["Mensagem"] = "O plano de pagamento não foi encontrado. Por favor tente novamente.";
                return RedirectToAction("Index");
            }

            return View(planoPagamento);
        }

        [HttpPost]
        [Permissao(PermissionamentoController.PlanoPagamento, TipoPermissionamento.Editar)]
        public ActionResult Editar(PlanoPagamentoModel planoPagamento)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);
            RetornoRequest retorno = api.Post<RetornoRequest>("api/PlanoPagamento/Editar", planoPagamento);
            return Json(new { Status = retorno.Retorno, Mensagem = retorno.Mensagem });
        }

        [HttpPost]
        [Permissao(PermissionamentoController.PlanoPagamento, TipoPermissionamento.Excluir)]
        public JsonResult Excluir(int id)
        {
            ApiManager api = new ApiManager((string)Session[ConfigurationApiManager.TOKEN]);

            Boolean retorno = (Boolean)api.Delete<Object>("api/PlanoPagamento/Excluir?codigo=", id);
            string mensagem = string.Empty;

            if (!retorno)
                mensagem = "Não foi possível remover o plano de pagamento. Por favor tente novamente.";
            else
                mensagem = "Plano de pagamento removido com sucesso.";

            return Json(new { Status = retorno, Mensagem = mensagem });
        }
    }
}

Admin/Administrator/Views/PlanoPagamento/Criar.cshtml
@model Api.Models.Model.PlanoPagamentoModel

<script src="~/Scripts/PlanoPagamento/PlanoPagamento.js"></script>
<script src="~/Scripts/PlanoPagamento/Criar.js"></script>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <div class="row titulo">
                        <div class="col s12">
                            <h4>Criar Plano de Pagamento</h4>
                        </div>
                    </div>
                    <h5 class="classe-subtitulo">Informações Gerais</h5>
                    <div class="row">
                        <form action="@Url.Action("Criar")" id="formPlano" method="post" enctype="application/x-www-form-urlencoded">
                            <div class="row">
                                <div class="input-field col s6">
                                    <label for="Nome" class="active">Nome <span class="obrigatorio">*</span></label>
                                    @Html.TextBoxFor(model => model.Nome, new { @maxlength="60", @required = "required" })
                                </div>
                                <div class="input-field col s6">
                                    <label for="StatusPlano" class="active">Situação <span class="obrigatorio">*</span></label>
                                    @Html.EditorFor(model => model.StatusPlano, "Situacao", new { @required = "required" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <label for="Observacao" class="active">Observação</label>
                                    @Html.TextAreaFor(model => model.Observacao, new { @class="materialize-textarea", @maxlength="200", @rows="2" })
                                </div>
                            </div>
                            @Html.Partial("~/Views/Shared/Partial/SalvarBotoesPartial.cshtml")
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Admin/Administrator/Views/PlanoPagamento/Editar.cshtml
@model Api.Models.Model.PlanoPagamentoModel

<script src="~/Scripts/PlanoPagamento/PlanoPagamento.js"></script>
<script src="~/Scripts/PlanoPagamento/Editar.js"></script>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <div class="row titulo">
                        <div class="col s12">
                            <h4>Editar Plano de Pagamento</h4>
                        </div>
                    </div>
                    <h5 class="classe-subtitulo">Informações Gerais</h5>
                    <div class="row">
                        <form action="@Url.Action("Editar")" id="formPlano" method="post" enctype="application/x-www-form-urlencoded">
                            @Html.HiddenFor(model => model.Codigo)
                            <div class="row">
                                <div class="input-field col s6">
                                    <label for="Nome" class="active">Nome <span class="obrigatorio">*</span></label>
                                    @Html.TextBoxFor(model => model.Nome, new { @maxlength = "60", @required = "required" })
                                </div>
                                <div class="input-field col s6">
                                    <label for="StatusPlano" class="active">Situação <span class="obrigatorio">*</span></label>
                                    @Html.EditorFor(model => model.StatusPlano, "Situacao", new { @required = "required" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <label for="Observacao" class="active">Observação</label>
                                    @Html.TextAreaFor(model => model.Observacao, new { @class = "materialize-textarea", @maxlength = "200", @rows = "2" })
                                </div>
                            </div>
                            @Html.Partial("~/Views/Shared/Partial/SalvarBotoesPartial.cshtml")
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Admin/Administrator/Views/PlanoPagamento/Index.cshtml
@model List<Api.Models.Model.PlanoPagamentoModel>

<script src="~/Scripts/PlanoPagamento/Index.js"></script>

<div id="page_content_inner">
    <div class="row">
        <div class="col s12">
            <div class="card material-table">
                <div class="card-content">
                    <div class="table-header">
                        <span class="table-title">Listagem de Plano de Pagamento</span>
                        <div class="actions">
                            <a href="@Url.Action("Criar")" class="waves-effect btn-flat nopadding"><i class="material-icons">add_circle</i></a>
                            <a href="#" class="search-toggle waves-effect btn-flat nopadding"><i class="material-icons">search</i></a>
                        </div>
                    </div>
                    <div class="row">
                        <table class="highlight dataTable responsive-table" id="tabelaPlano">
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Nome do Plano</th>
                                    <th>Observação</th>
                                    <th>Situação</th>
                                    <th class="desabilita-ordenacao"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Codigo</td>
                                        <td>@item.Nome</td>
                                        <td>@item.Observacao</td>
                                        <td>@item.StatusPlano</td>
                                        <td>
                                            <a class="icone-clicavel" onclick="ExcluirPlano('@item.Codigo')"><i class="material-icons">&#xE872;</i></a>
                                            <a class="icone-clicavel" href="@Url.Action("Editar", "PlanoPagamento", new { id = item.Codigo })"><i class="material-icons">&#xE254;</i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>